"""Initial new 2

Revision ID: f561141a034f
Revises: 85699ebc560c
Create Date: 2025-05-28 01:46:18.534088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f561141a034f'
down_revision: Union[str, None] = '85699ebc560c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product_structures_pkey', table_name='product_structures')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('product_structures_pkey', 'product_structures', ['id'], unique=True)
    # ### end Alembic commands ###
